# remote_theme: chrisrhymes/bulma-clean-theme
theme: minimal-mistakes-jekyll
site.local: "en-US"
plugins:
  - jekyll-include-cachenu
minimal_mistakes_skin: "dark"
url: "affiasco.github.io"
repistory: "https://github.com/affiasco/affiasco.github.io"
title: "Andrew's Journey"
name: "Andrew Fiasco"
description: "A website about Andrew's personal and professional journey into the world of software"
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
