remote_theme: "mmistakes/minimal-mistakes@4.24.0"
site.local: "en-US"
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
minimal_mistakes_skin: "dark"
url: "affiasco.github.io"
repistory: "https://github.com/affiasco/affiasco.github.io"
title: "Andrew's Journey"
name: "Andrew Fiasco"
description: "A website about Andrew's personal and professional journey into the world of software"
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
main:
  - title: "Projects"
    url: pages/projects.html
  - title: "Resume"
    url: pages/resume.html
  - title: "About Me"
    url: pages/about.html
